# Generated by Django 2.2.1 on 2019-09-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
