# Generated by Django 2.2.1 on 2019-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_orderinfo_payorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='goods_price',
            field=models.FloatField(default=10),
        ),
    ]
