# Generated by Django 2.2.1 on 2019-10-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Saller', '0006_valid_code'),
        ('Buyer', '0006_auto_20191005_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, verbose_name='收件人')),
                ('detail_addr', models.TextField(verbose_name='详细地址')),
                ('u_code', models.CharField(max_length=7, verbose_name='邮编')),
                ('phone', models.CharField(max_length=14, verbose_name='手机号')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Saller.LoginUser')),
            ],
        ),
    ]
