# Generated by Django 2.2.1 on 2019-10-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_recaddress_address_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='orderinfo_status',
            field=models.IntegerField(default=0, verbose_name='订单状态'),
            preserve_default=False,
        ),
    ]
