# Generated by Django 2.2.1 on 2019-10-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0009_orderinfo_orderinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='orderinfo_status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '待发货'), (3, '待收货'), (4, '完成'), (5, '拒收')], verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='payorder',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '待发货'), (3, '待收货'), (4, '完成'), (5, '拒收')], verbose_name='订单状态'),
        ),
    ]
