# Generated by Django 2.2.1 on 2019-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0010_auto_20191010_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='number',
            field=models.CharField(default='0', max_length=32, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='orderinfo_status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '待发货'), (3, '待收货'), (4, '完成'), (5, '拒收')], default=0, verbose_name='订单状态'),
        ),
    ]
